version: '3'

services:
  dev-db:
    container_name: draperweb-dev-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: draperweb-dev
    ports:
      - 5439:5432
    volumes:
      - dev-db-data:/var/lib/postgresql/data

volumes:
  dev-db-data: